import org.gradle.internal.os.OperatingSystem

plugins {
    id "java-library"
}

base {
    group = "com.darkyen"
    archivesName = "experimentation"
    version = "0.0"
}

switch (OperatingSystem.current()) {
    case OperatingSystem.LINUX:
        project.ext.lwjglNatives = "natives-linux"
        def osArch = System.getProperty("os.arch")
        if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
            project.ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
        } else if  (osArch.startsWith("ppc")) {
            project.ext.lwjglNatives += "-ppc64le"
        } else if  (osArch.startsWith("riscv")) {
            project.ext.lwjglNatives += "-riscv64"
        }
        break
    case OperatingSystem.MAC_OS:
        project.ext.lwjglNatives = System.getProperty("os.arch").startsWith("aarch64") ? "natives-macos-arm64" : "natives-macos"
        break
    case OperatingSystem.WINDOWS:
        def osArch = System.getProperty("os.arch")
        project.ext.lwjglNatives = osArch.contains("64")
                ? "natives-windows${osArch.startsWith("aarch64") ? "-arm64" : ""}"
                : "natives-windows-x86"
        break
}

repositories {
    mavenCentral()
}

sourceSets {
    demo {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

dependencies {
    implementation("com.badlogicgames.gdx:gdx:$gdx_version")
    implementation("com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdx_version")
    implementation("com.badlogicgames.gdx:gdx-platform:$gdx_version:natives-desktop")
    implementation("com.badlogicgames.gdx:gdx-freetype:$gdx_version")
    implementation("com.badlogicgames.gdx:gdx-freetype-platform:$gdx_version:natives-desktop")

    implementation platform("org.lwjgl:lwjgl-bom:$lwjgl_version")
    implementation("org.lwjgl:lwjgl-freetype")
    implementation("org.lwjgl:lwjgl-harfbuzz")
    runtimeOnly("org.lwjgl:lwjgl-freetype::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-harfbuzz::$lwjglNatives")

    demoImplementation(sourceSets.main.output)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.register("runDemo", JavaExec) {
    classpath = sourceSets.demo.runtimeClasspath
    mainClass = "com.darkyen.libgdx.HarfBuzzTest"
}

testing {
    suites {
        test {
            useJUnitJupiter()
        }
    }
}
